{
 "title": "Graylog Server",
 "description": "Prometheus Graylog exporter metrics.",
 "tags": [
  "prometheus",
  "graylog"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(gl_system_job_manager_executor_thread,instance)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(gl_log_appenders_total{instance=\"$instance\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input Buffer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gl_buffer_usage{type=\"input\", instance=\"$instance\"}",
     "legendFormat": "{{instance}} Used"
    },
    {
     "expr": "gl_buffer_size{type=\"input\", instance=\"$instance\"}",
     "legendFormat": "{{instance}} Size"
    }
   ]
  },
  {
   "title": "Process Buffer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gl_buffer_usage{type=\"process\", instance=\"$instance\"}",
     "legendFormat": "{{instance}} Used"
    },
    {
     "expr": "gl_buffer_size{type=\"process\", instance=\"$instance\"}",
     "legendFormat": "{{instance}} Size"
    }
   ]
  },
  {
   "title": "Output Buffer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gl_buffer_usage{type=\"output\", instance=\"$instance\"}",
     "legendFormat": "{{instance}} Used"
    },
    {
     "expr": "gl_buffer_size{type=\"output\", instance=\"$instance\"}",
     "legendFormat": "{{instance}} Size"
    }
   ]
  },
  {
   "title": "Process Buffer Process Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_buffer_process_time{instance=\"$instance\", type=\"process\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Output Buffer Process Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_buffer_process_time{instance=\"$instance\", type=\"output\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Messages received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(gl_buffer_incoming_messages_total{type=\"input\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Per Stream",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(gl_stream_incoming_messages_total{instance=\"$instance\"}[$__rate_interval]) > 0",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Per Stream",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(gl_stream_incoming_messages_total{instance=\"$instance\"}[$__rate_interval]) > 0",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Output to Indexer",
   "type": "timeseries",
   "description": "Messages written to indexer, such as Elasticsearch or OpenSearch",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(gl_elasticsearch_output_writes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BlockingBatchedESOutput.processTime",
   "type": "timeseries",
   "description": "Amount of time graylog is waiting for OpenSearch to save messages from batch",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_blocking_elasticsearch_output_process_time{instance=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Output Msgs Failures",
   "type": "timeseries",
   "description": "Typically these will be indexing errors. Number of messages that failed to output to indexer/OpenSearch",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(gl_elasticsearch_output_failures_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "HTTP Worker Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "description": "This is the number of HTTP Worker Threads of each type.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gl_jersey_http_worker_executor_thread{node=\"$node\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}} {{quantile}}% {{type}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "This is the length of time that an HTTP Worker Thread took to execute from start to finish in seconds (s).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_jersey_http_worker_duration{node=\"$node\",quantile=\"0.99\"}",
     "legendFormat": "{{instance}} {{quantile}}%"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "This is the total number of HTTP Requests of 2 types; submitted & completed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(gl_jersey_http_worker_executor_thread_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  { "title": "Journal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Journal Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gl_journal_utilization_ratio{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Journal Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "gl_journal_size{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Journal Uncommitted Entries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gl_journal_entries_uncommitted{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}